{"uuid": "7c1adc7a-65ff-4083-8cb1-9ee8732ccd2f", "children": ["b32862bd-1bb3-463b-bae2-74b9c00c25b2", "e1403500-3fcf-4db2-97dd-c4f4d23c8957", "336e4b54-7a91-4f12-ab0e-3888ab253041", "e6d45ef4-c10b-44fc-aabf-a246175abfcf", "a6af9e81-cc83-43e1-b9a6-a5305a91f6a7", "56e25d9a-7d74-4c90-b74b-bd7781659726"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bandainamcoent.ro', port=443): Max retries exceeded with url: /ro/careers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7df4b176d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_bandainamco.py\", line 14, in get_job_details\n    scraper_data = bandainamcoScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/bandainamco_scraper.py\", line 29, in scraper\n    soup = GetStaticSoup(\"https://www.bandainamcoent.ro/ro/careers/\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/__utils/req_bs4_shorts.py\", line 35, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1706332263369, "stop": 1706332263693}], "start": 1706332263369, "stop": 1706332264157}