{"uuid": "2a2c7fd6-8c08-4aba-b048-8be3003e6d5e", "children": ["dd9e8950-3ea3-447b-ab63-519bfbd7eb1f", "1472287b-9eb9-4190-8055-f6f9312e092a", "e99ee2f6-160f-4e2e-8ba4-73780c993255", "7e2ac8c7-b58a-47a7-bf36-9bb1b7ae0873", "52155ea7-cfd1-4c5d-ac9c-d6aee6303fa3", "33eb79e8-ec0e-4239-ab4e-230e394b4052"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bandainamcoent.ro', port=443): Max retries exceeded with url: /ro/careers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5835e083a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_bandainamco.py\", line 14, in get_job_details\n    scraper_data = bandainamcoScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/bandainamco_scraper.py\", line 29, in scraper\n    soup = GetStaticSoup(\"https://www.bandainamcoent.ro/ro/careers/\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/__utils/req_bs4_shorts.py\", line 35, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1706073161663, "stop": 1706073161892}], "start": 1706073161663, "stop": 1706073162390}