{"uuid": "c49befd3-95db-4ba1-a922-72fcbb2eeab1", "children": ["cfc8e6b5-9785-49c7-af2e-4fd965d69d7f", "285ad8c6-381a-480e-95e1-363e60e99bed", "00c95f20-6342-43b4-8be4-1e11c8cd153d", "2482c23b-ea85-4a85-abbf-524caa135ffd", "e30d1b48-7d1b-40be-9761-2a56f96612ee", "826a2bb9-eb13-47e6-a153-3199a27562a8"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bandainamcoent.ro', port=443): Max retries exceeded with url: /ro/careers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4f5af9af20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_bandainamco.py\", line 14, in get_job_details\n    scraper_data = bandainamcoScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/bandainamco_scraper.py\", line 29, in scraper\n    soup = GetStaticSoup(\"https://www.bandainamcoent.ro/ro/careers/\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/__utils/req_bs4_shorts.py\", line 35, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1705986774360, "stop": 1705986774717}], "start": 1705986774360, "stop": 1705986775240}