{"uuid": "8794ce23-fbaa-4aab-b45f-3304ffdcf4fe", "children": ["e437b33c-c35b-4612-97cb-4be7fc8ab681", "bb6f1cba-0feb-44f9-b583-e06f6e776246", "df511564-63ae-4571-aa9e-230eee08b17e", "b7b982ab-80a6-4eb2-952d-f377a33f02ce", "4df3f3e4-3210-4416-b048-1a19a9f7f53a", "82235d49-0915-4506-92c2-8ce5c99f70ce"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bandainamcoent.ro', port=443): Max retries exceeded with url: /ro/careers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa763f99c90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_bandainamco.py\", line 14, in get_job_details\n    scraper_data = bandainamcoScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/bandainamco_scraper.py\", line 29, in scraper\n    soup = GetStaticSoup(\"https://www.bandainamcoent.ro/ro/careers/\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/__utils/req_bs4_shorts.py\", line 35, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1705900391331, "stop": 1705900391665}], "start": 1705900391331, "stop": 1705900392138}