{"uuid": "d7c5c60d-681e-496a-b0e1-0a7f0bc02f71", "children": ["8cd46e0a-7c69-4a8c-9b80-3e05508e6367", "87f4ccc9-0240-4978-8e90-c28689edc3dd", "67ffdd30-c438-4086-aa64-6ee6f1626df5", "e2eddf16-0e83-4609-af2f-236eff01ee6a", "868d9b3b-6d6d-4a13-99b8-a2ed9e099c98", "78df4940-e3a4-456f-8449-84c209b35051", "ad5003cd-6f32-4d9b-b0fa-7fbe289f328c"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bandainamcoent.ro', port=443): Max retries exceeded with url: /ro/careers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbfc47829e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_bandainamco.py\", line 14, in get_job_details\n    scraper_data = bandainamcoScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/bandainamco_scraper.py\", line 29, in scraper\n    soup = GetStaticSoup(\"https://www.bandainamcoent.ro/ro/careers/\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/scrapers/__utils/req_bs4_shorts.py\", line 36, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1706645540954, "stop": 1706645541192}], "start": 1706645540954, "stop": 1706645541730}